#!/bin/bash
if [ ! $(command -v wget) ]; then
    echo "please install wget"
    exit 1
fi

if [ ! $(command -v make) ]; then
    echo "please install make"
    exit 1
fi

if [ ! $(command -v g++) ]; then
    echo "please install make"
    exit 1
fi

if [ ! $(command -v vim) ]; then
    echo "please install vim"
    exit 1
fi

if [ -f  /bin/checker ]; then
    echo -e "\e[33mwarning: remove /bin/checker\e[0m"
    sudo rm /bin/checker
fi
if [ -f  /usr/bin/checker ]; then
    echo -e "\e[33mwarning: remove /usr/bin/checker\e[0m"
    sudo rm /usr/bin/checker
fi
if [ -f  /usr/local/bin/checker ]; then
    echo -e "\e[33mwarning: remove /usr/local/bin/checker\e[0m"
    sudo rm /usr/local/bin/checker
fi
if [ -f /tmp/checker/source ]; then
    rm -rf /tmp/checker/source
fi

echo -e "\e[32m[copy file] ...\e[0m" && \
rm -rf /tmp/checker/source/ && \
mkdir -p /tmp/checker/source/ && \
cp -r ./ /tmp/checker/source/ && \
cd /tmp/checker/source/ && \

echo -e "\e[32m[compile] ...\e[0m" && \
make $1 && \
echo -e "\e[32m[create link] ...\e[0m" && \
sudo cp ./checker /usr/local/bin/checker && \
sudo chmod 777 /usr/local/bin/checker && \

ret=$?
if [ $ret != 0 ]; then
    echo -e "\n\e[31mshell return $ret, failed.\e[0m"
fi
exit $ret
